[BACKUP]
MARK_DIR="/home/user/backup/marks"
WATCH_DIRS="blog,nginx-conf,database"
TARGET_DIR="/mnt/remote/backup"
BACKUP_NUM=3
RETRY_COUNT=2
MONITOR_RESTART_RETRIES=3

[blog]
TYPE="DIR"
PATH="/var/www/blog"

[nginx-conf]
TYPE="DIR"
PATH="/etc/nginx/conf.d"

[database]
TYPE="DIR"
PATH="/var/lib/mysql"
